# Logistic regression

In [60]:
import pandas as pd 
import seaborn as sns

from sklearn.linear_model import LogisticRegression

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score, precision_score

In [61]:
heart_df = pd.read_csv("heart.csv")
# heart_df.info()   
# heart_df["target"].nunique()
heart_df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [62]:
X = heart_df.drop(columns=["target"])
y = heart_df["target"]

X.head()

   age  sex  cp  trestbps  chol  fbs  ...  thalach  exang  oldpeak  slope  ca  thal
0   63    1   3       145   233    1  ...      150      0      2.3      0   0     1
1   37    1   2       130   250    0  ...      187      0      3.5      0   0     2
2   41    0   1       130   204    0  ...      172      0      1.4      2   0     2
3   56    1   1       120   236    0  ...      178      0      0.8      2   0     2
4   57    0   0       120   354    0  ...      163      1      0.6      2   0     2

[5 rows x 13 columns]

In [ ]:
# Test train split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)



#check equal split for binary classfication - 50/50 for both class

# y_train[y_train == 1]             #122
# y_train[y_train == 0]             #109

132    1
75     1
59     1
93     1
6      1
      ..
121    1
20     1
71     1
106    1
102    1
Name: target, Length: 133, dtype: int64

In [64]:
model = LogisticRegression(max_iter=10000)

model.fit(X_train, y_train)

y_pred = model.predict(X_test)

precision = precision_score(y_test, y_pred)

print("Precision score : ", precision)

Precision score :  0.8787878787878788